### ISSUE TITLE
Library needs to be updated

### ISSUE THREAD

**Issue by jehajj** [Bhoos/react-native-theming#15]
I am using this library but It keeps on showing warnings regarding components lifecycle. Will you be able to update the code?
![image](https://user-images.githubusercontent.com/36712924/68109365-0b345d80-fef3-11e9-84fd-394f155932e4.png)

**Comment by syaau** [comment]
Sure I will look into this, I was planning to update it with hooks anyway.

**Comment by dapicester** [comment]
The warnings  have been fixed in 1.0.21. @syaau I believe you can close this.
