### ISSUE TITLE
Passing forwardRef

### ISSUE THREAD

**Issue by atifaziz1** [Bhoos/react-native-theming#29]
Hi, 
I am passing TextInput into ThemedComponent.I need pass ref to child component which is TextInput.
I need your help that how i can pass ref or forwardRef to child component.
Bellow is code that how i am exactly doing.

const textInput = createThemedComponent(**TextInput**);

**Comment by syaau** [comment]
@atifaziz1  I have just published 1.0.19 with ref forwarding, Please check and let me know if there is any issue.

**Comment by atifaziz1** [comment]
@syaau Thanks for your response. I saw updated version but i didn't get really how to pass forward ref.
It could be great help if you can guide me.
Thanks.

**Comment by syaau** [comment]
@atifaziz1  You can use Your TextInput component like regular TextInput component
```jsx
const ThemedTextInput = createThemedComponent(TextInput);


function SomeComponent() {
  const ref = useRef();
  // Focus TextInput on mount (Just an example, You should use `autoFocus` props for this particular purpose)
  useEffect(() => { ref.current.focus(); }, []);
  return (
     <ThemedTextInput ref={ref} ... />
  );
}
```

**Comment by atifaziz1** [comment]
@syaau Thanks .... (Y)

**Comment by atifaziz1** [comment]
Hi @syaau !

```
const ThemedTextInput = createThemedComponent(TextInput);
export function MyTextInput() {
  const ref = React.useRef();
  return <ThemedTextInput ref={ref} />;
}
```

and importing in component like

```
<MyTextInput
ref={ref => (this.ref = ref)}
/>
```

but ref is undefined , please let me what is the wrong.?

**Comment by syaau** [comment]
@atifaziz1  You don't need the `MyTextInput` component, you should use the `ThemedTextInput` component wherever you need it.

**Comment by atifaziz1** [comment]
@syaau like this.??

```
const ThemedTextInput = createThemedComponent(TextInput);
const ref = React.useRef();
 <ThemedTextInput ref={ref} />;

export{
ThemedTextInput
}
```

and 

```
<ThemedTextInput
ref={ref => (this.ref = ref)}
/>
```

**Comment by syaau** [comment]
```javascript
export const ThemedTextInput = createThemedComponent(TextInput);
```
and then use `ThemedTextInput` like a normal TextInput component but with themed styles.

**Comment by atifaziz1** [comment]
@syaau , i was doing like this before , the problem is ref is undefined, i need ref to focus TextInput.

**Comment by syaau** [comment]
@atifaziz1 Here is a sample working code:
https://snack.expo.io/sVJYbyuhW

**Comment by atifaziz1** [comment]
Hi @syaau , Hope you are fine.

Same code you mentioned above is not working for me. Please look into this.
"react-native-theming": "1.0.19",

<img width="444" alt="Screen Shot 1441-08-23 at 3 00 57 PM" src="https://user-images.githubusercontent.com/37400835/79454242-88601480-7ff3-11ea-8603-df839b1d065d.png">

**Comment by syaau** [comment]
@atifaziz1 Can you share me your code snippet ?

**Comment by atifaziz1** [comment]
`import React, { useRef } from 'react';
import { Text, View, StyleSheet, TextInput, TouchableOpacity } from 'react-native';
import { createThemedComponent } from 'react-native-theming';

const ThemedTextInput = createThemedComponent(TextInput);

const Input = () => {
  const ref = useRef();
    function focus() {
    ref.current.focus();
  }

  return (
    <View style={styles.container}>
      <ThemedTextInput ref={ref} style={{ backgroundColor: 'red' }} />
      <TouchableOpacity onPress={focus}>
        <Text style={styles.paragraph}>{'Set Focus'}</Text>
      </TouchableOpacity>
    </View>
  );
};

export default Input;

const styles = StyleSheet.create({
  container: {
    height: 70,
    justifyContent: 'center',
    paddingTop: 10,
    padding: 8,
  },
  paragraph: {
    margin: 24,
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    color: 'black',
  },
});
`

**Comment by syaau** [comment]
Where are you calling the focus function ?

**Comment by atifaziz1** [comment]
I don't know why complete code is not showing you. let me send again.

`return (
    <View style={styles.container}>
      <ThemedTextInput ref={ref} style={{ backgroundColor: 'red' }} />
      <TouchableOpacity onPress={focus}>
        <Text style={styles.paragraph}>{'Set Focus'}</Text>
      </TouchableOpacity>
    </View>
  );`

**Comment by syaau** [comment]
Looks like your package has not updated to latest version 1.0.19, Make sure you have installed 1.0.19, and then reset cache once with `react-native start --reset-cache`

**Comment by atifaziz1** [comment]
@syaau .. Thank you sooooooo much, issue has been resolved.

**Comment by jonathanroze** [comment]
Not working on 1.0.21 :/ 

My code: 

```
import React from 'react';
import {createThemedComponent} from 'react-native-theming';
import {TextInput as TI} from "react-native";

const ToThemed = createThemedComponent(TI, ['style', 'placeholderTextColor']);

export function TextInput(props: any) {
    const {style} = props;

    return (
        <ToThemed style={style} {...props} />
    );
}

```

And when I use this component 

```
<TextInput
                                    clearButtonMode="always"
                                    autoCompleteType="name"
                                    onChangeText={text => {
                                        this.props.store.setTextInput(text);
                                        this.props.store.fetch(true);
                                    }}
                                    ref={this.searchInput}
                                    style={{height: 40, paddingLeft: 5, color: '@textColor'}}
                                    placeholderTextColor={"@placeholderTextColor"}
                                    value={this.props.store.textInput}
                                    placeholder="John Smith..."
                                />
```
