### ISSUE TITLE
How can i apply placeholderTextColor text color based on theme.

### ISSUE THREAD

**Issue by jariwalabhavesh** [Bhoos/react-native-theming#4]
How can we implement placeholderTextColor dynamically

eg. 

Theme File
```
const AppThemes = [
  createTheme({
    fontColor: '#222222',
    backgroundColor: '#FFFFFF',
   rgbaBackground: '255,255,255'
  }, 'Theme1'),
  createTheme({
    backgroundColor: '#222222',
   fontColor: '#FFFFFF',
   rgbaBackground: '0,0,0'
  }, 'Theme1'),
];
```
Component File
import { TextInput } from 'react-native'
```
const Input = createThemedComponent(TextInput);
.
.
<Input placeholder='Email' placeholderTextColor='@fontColor' style={styles.inputCtrl} />
.
.
.
```
IN above example placeholderTextColor is not updating on theme switching. anything we can do it with or implement it like We have in <Image source='@backgroundUImage'>

Any idea what is issue or is there already feature in library??

Thank you in advance

**Comment by syaau** [comment]
@jariwalabhavesh This feature is already there in the library. We have used this to change the image source based on the Theme. You seem to have used it correctly and should work when you change the theme. I am not sure, but you seem to have Themes with the same name 'Theme1' on AppThemes. May be that is the problem. Check this documentation for props support in Theme. https://github.com/Bhoos/react-native-theming#create-your-themed-view

**Comment by syaau** [comment]
Oh and I forgot to mention, you have to provide the props that need to be themed when creating Themed Component, in your case:
```
const Input = createThemedComponent(TextInput, ['placeholderTextColor'])
```
This should solve your issue.

**Comment by jariwalabhavesh** [comment]
@syaau 
Thanks for quick response, I checked and it is working. Thanks again.
